import { useMemo, useState } from 'react'
import { Bank, CaretRight, CheckCircle, CurrencyCircleDollar, MagnifyingGlass, Plus, Receipt, ShieldWarning } from '@phosphor-icons/react'
import { Alert, Avatar, Button, Card, Descriptions, Drawer, Flex, Form, Input, InputNumber, Modal, Select, Space, Table, Tag, Typography, message } from 'antd'
import type { TableProps } from 'antd'
import AdminLayout, { type AdminPage } from './AdminLayout'
import { AdminPageHeader, AdminSummary } from './AdminPageKit'

type InvoiceStatus = 'Chưa thanh toán' | 'Đã thanh toán' | 'Quá hạn' | 'Đã hủy'
type InvoiceRecord = { id: number; code: string; studentCode: string; studentName: string; className: string; course: string; amount: number; issuedAt: string; dueDate: string; status: InvoiceStatus; paidAt?: string; paymentMethod?: string; cancelReason?: string }
type Props = { onLogout: () => void; onNavigate: (page: AdminPage) => void; onNavigateHome: () => void }
const students = [{ code: 'HV-0248', name: 'Nguyễn Khánh Linh', className: 'A2 Giao tiếp', course: 'Tiếng Anh A2', amount: 3200000 }, { code: 'HV-0217', name: 'Trần Gia Huy', className: 'B1 Tổng quát', course: 'Tiếng Anh B1', amount: 4200000 }, { code: 'HV-0196', name: 'Lê Minh Anh', className: 'IELTS 6.5', course: 'Luyện thi IELTS 6.5', amount: 6800000 }, { code: 'HV-0151', name: 'Võ Hoàng Nam', className: 'TOPIK I - K05', course: 'Tiếng Hàn TOPIK I', amount: 4900000 }, { code: 'HV-0138', name: 'Đặng Thu Trang', className: 'HSK 3 - T04', course: 'Tiếng Trung HSK 3', amount: 4600000 }]
const initialInvoices: InvoiceRecord[] = [
  { id: 1, code: 'HD-2026-041', studentCode: 'HV-0248', studentName: 'Nguyễn Khánh Linh', className: 'A2 Giao tiếp', course: 'Tiếng Anh A2', amount: 3200000, issuedAt: '2026-08-12', dueDate: '2026-09-25', status: 'Chưa thanh toán' },
  { id: 2, code: 'HD-2026-040', studentCode: 'HV-0217', studentName: 'Trần Gia Huy', className: 'B1 Tổng quát', course: 'Tiếng Anh B1', amount: 4200000, issuedAt: '2026-08-08', dueDate: '2026-09-10', status: 'Đã thanh toán', paidAt: '2026-09-08', paymentMethod: 'Chuyển khoản' },
  { id: 3, code: 'HD-2026-039', studentCode: 'HV-0196', studentName: 'Lê Minh Anh', className: 'IELTS 6.5', course: 'Luyện thi IELTS 6.5', amount: 6800000, issuedAt: '2026-08-01', dueDate: '2026-09-05', status: 'Quá hạn' },
  { id: 4, code: 'HD-2026-038', studentCode: 'HV-0173', studentName: 'Phạm Quang Duy', className: 'A2 Giao tiếp', course: 'Tiếng Anh A2', amount: 3200000, issuedAt: '2026-07-28', dueDate: '2026-08-28', status: 'Đã thanh toán', paidAt: '2026-08-24', paymentMethod: 'Tiền mặt' },
  { id: 5, code: 'HD-2026-037', studentCode: 'HV-0151', studentName: 'Võ Hoàng Nam', className: 'TOPIK I - K05', course: 'Tiếng Hàn TOPIK I', amount: 4900000, issuedAt: '2026-07-20', dueDate: '2026-09-20', status: 'Chưa thanh toán' },
  { id: 6, code: 'HD-2026-036', studentCode: 'HV-0138', studentName: 'Đặng Thu Trang', className: 'HSK 3 - T04', course: 'Tiếng Trung HSK 3', amount: 4600000, issuedAt: '2026-07-18', dueDate: '2026-08-20', status: 'Đã hủy', cancelReason: 'Học viên chuyển sang khóa học khác.' },
]
const money = (value: number) => `${new Intl.NumberFormat('vi-VN').format(value)}đ`
const date = (value: string) => new Intl.DateTimeFormat('vi-VN').format(new Date(`${value}T00:00:00`))
const colors: Record<InvoiceStatus, string> = { 'Chưa thanh toán': 'gold', 'Đã thanh toán': 'green', 'Quá hạn': 'red', 'Đã hủy': 'default' }

function AdminInvoices({ onLogout, onNavigate, onNavigateHome }: Props) {
  const [invoices, setInvoices] = useState(initialInvoices)
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<'Tất cả' | InvoiceStatus>('Tất cả'); const [className, setClassName] = useState('Tất cả')
  const [selected, setSelected] = useState<InvoiceRecord | null>(null); const [creating, setCreating] = useState(false)
  const [form] = Form.useForm<{ studentCode: string; dueDate: string }>(); const [messageApi, contextHolder] = message.useMessage()
  const [modal, modalContextHolder] = Modal.useModal()
  const selectedStudentCode = Form.useWatch('studentCode', form)
  const data = useMemo(() => invoices.filter((item) => (!query.trim() || [item.code, item.studentCode, item.studentName, item.className].some((value) => value.toLocaleLowerCase('vi').includes(query.trim().toLocaleLowerCase('vi')))) && (status === 'Tất cả' || item.status === status) && (className === 'Tất cả' || item.className === className)), [className, invoices, query, status])
  const create = ({ studentCode, dueDate }: { studentCode: string; dueDate: string }) => {
    const student = students.find((item) => item.code === studentCode) ?? students[0]
    if (invoices.some((item) => item.studentCode === studentCode && item.className === student.className && item.status !== 'Đã hủy')) { messageApi.error('Học viên đã có hóa đơn còn hiệu lực cho lớp này.'); return }
    const id = Math.max(...invoices.map((item) => item.id)) + 1; const invoice: InvoiceRecord = { id, code: `HD-2026-${String(id + 41).padStart(3, '0')}`, studentCode, studentName: student.name, className: student.className, course: student.course, amount: student.amount, issuedAt: new Date().toISOString().slice(0, 10), dueDate, status: 'Chưa thanh toán' }
    setInvoices((current) => [invoice, ...current]); setCreating(false); messageApi.success('Đã tạo hóa đơn.')
  }
  const pay = (invoice: InvoiceRecord) => modal.confirm({ title: 'Xác nhận thanh toán?', content: `${invoice.studentName} · ${money(invoice.amount)}`, okText: 'Xác nhận', onOk: () => { const next = { ...invoice, status: 'Đã thanh toán' as const, paidAt: new Date().toISOString().slice(0, 10), paymentMethod: 'Chuyển khoản' }; setInvoices((current) => current.map((item) => item.id === invoice.id ? next : item)); setSelected(next); messageApi.success('Đã xác nhận thanh toán.') } })
  const cancel = (invoice: InvoiceRecord) => { if (invoice.status === 'Đã thanh toán') { messageApi.error('Không thể hủy hóa đơn đã thanh toán.'); return }; modal.confirm({ title: 'Hủy hóa đơn?', content: invoice.code, okButtonProps: { danger: true }, onOk: () => { const next = { ...invoice, status: 'Đã hủy' as const, cancelReason: 'Hủy theo yêu cầu của quản trị viên.' }; setInvoices((current) => current.map((item) => item.id === invoice.id ? next : item)); setSelected(next); messageApi.success('Đã hủy hóa đơn.') } }) }
  const columns: TableProps<InvoiceRecord>['columns'] = [
    { title: 'Hóa đơn', key: 'invoice', render: (_, item) => <div><Typography.Text strong>{item.code}</Typography.Text><br /><Typography.Text type="secondary">{date(item.issuedAt)}</Typography.Text></div> },
    { title: 'Học viên', key: 'student', render: (_, item) => <div className="admin-entity"><Avatar shape="square">{item.studentName.split(' ').slice(-2).map((part) => part[0]).join('')}</Avatar><div><strong>{item.studentName}</strong><small>{item.studentCode}</small></div></div> },
    { title: 'Lớp học', dataIndex: 'className' }, { title: 'Số tiền', dataIndex: 'amount', render: (value) => <Typography.Text strong>{money(value)}</Typography.Text> }, { title: 'Hạn thanh toán', dataIndex: 'dueDate', render: date },
    { title: 'Trạng thái', dataIndex: 'status', render: (value: InvoiceStatus) => <Tag color={colors[value]}>{value}</Tag> }, { title: '', key: 'action', width: 52, render: (_, item) => <Button icon={<CaretRight />} onClick={() => setSelected(item)} aria-label={`Xem hóa đơn ${item.code}`} /> },
  ]
  return <AdminLayout activePage="invoices" mainId="invoice-management" onLogout={onLogout} onNavigate={onNavigate} onNavigateHome={onNavigateHome}>
    {contextHolder}{modalContextHolder}<AdminPageHeader kicker="Tài chính học vụ" title="Quản lý học phí" description="Theo dõi hóa đơn, công nợ và điều kiện dự thi của học viên." actions={<Button type="primary" icon={<Plus />} onClick={() => { setCreating(true); form.setFieldsValue({ studentCode: students[0].code, dueDate: '2026-10-15' }) }}>Tạo hóa đơn</Button>} />
    <AdminSummary items={[{ label: 'Đã thu', value: money(invoices.filter((item) => item.status === 'Đã thanh toán').reduce((sum, item) => sum + item.amount, 0)).replace('đ', ''), detail: 'VNĐ đã xác nhận thanh toán', icon: <Bank weight="duotone" />, tone: 'success' }, { label: 'Công nợ', value: money(invoices.filter((item) => ['Chưa thanh toán', 'Quá hạn'].includes(item.status)).reduce((sum, item) => sum + item.amount, 0)).replace('đ', ''), detail: 'VNĐ chưa hoàn tất', icon: <CurrencyCircleDollar weight="duotone" /> }, { label: 'Hóa đơn quá hạn', value: invoices.filter((item) => item.status === 'Quá hạn').length, detail: 'Tạm khóa quyền dự thi', icon: <ShieldWarning weight="duotone" />, tone: 'danger' }]} />
    <Card className="admin-table-card" title="Danh sách hóa đơn" extra={<Space wrap><Input allowClear prefix={<MagnifyingGlass />} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Mã, học viên hoặc lớp" /><Select value={status} onChange={setStatus} options={['Tất cả', 'Chưa thanh toán', 'Đã thanh toán', 'Quá hạn', 'Đã hủy'].map((value) => ({ value, label: value }))} /><Select value={className} onChange={setClassName} options={['Tất cả', ...new Set(invoices.map((item) => item.className))].map((value) => ({ value, label: value }))} /></Space>}><Table rowKey="id" columns={columns} dataSource={data} scroll={{ x: 980 }} pagination={{ pageSize: 6, showTotal: (total) => `${total} hóa đơn` }} /></Card>
    <Drawer size={450} title="Chi tiết hóa đơn" open={Boolean(selected)} onClose={() => setSelected(null)}>{selected && <><Flex align="center" gap={12}><Receipt size={36} /><div><Typography.Title className="admin-drawer-title" level={3}>{selected.code}</Typography.Title><Typography.Text type="secondary">{selected.studentName} · {selected.studentCode}</Typography.Text></div></Flex><Card style={{ marginTop: 22, background: '#e8f1e8' }}><Flex justify="space-between"><Typography.Text>Tổng học phí</Typography.Text><Typography.Title level={3} style={{ margin: 0 }}>{money(selected.amount)}</Typography.Title></Flex></Card><Descriptions bordered column={1} size="small" style={{ marginTop: 18 }} items={[{ key: 'course', label: 'Khóa học', children: selected.course }, { key: 'issued', label: 'Ngày tạo', children: date(selected.issuedAt) }, { key: 'due', label: 'Hạn thanh toán', children: date(selected.dueDate) }, ...(selected.paidAt ? [{ key: 'paid', label: 'Đã thanh toán', children: `${date(selected.paidAt)} · ${selected.paymentMethod}` }] : []), ...(selected.cancelReason ? [{ key: 'cancel', label: 'Lý do hủy', children: selected.cancelReason }] : [])]} /><Alert style={{ marginTop: 18 }} type={selected.status === 'Đã thanh toán' ? 'success' : 'warning'} showIcon title={selected.status === 'Đã thanh toán' ? 'Đã mở khóa điều kiện tài chính' : 'Tạm khóa do học phí'} /><Space orientation="vertical" style={{ width: '100%', marginTop: 18 }}>{['Chưa thanh toán', 'Quá hạn'].includes(selected.status) && <Button block type="primary" icon={<CheckCircle />} onClick={() => pay(selected)}>Xác nhận thanh toán</Button>}<Button block danger onClick={() => cancel(selected)} disabled={selected.status === 'Đã hủy'}>Hủy hóa đơn</Button></Space></>}</Drawer>
    <Modal title="Tạo hóa đơn" open={creating} onCancel={() => setCreating(false)} onOk={() => form.submit()} okText="Tạo hóa đơn" destroyOnHidden><Form form={form} layout="vertical" onFinish={create} style={{ marginTop: 20 }}><Form.Item name="studentCode" label="Học viên" rules={[{ required: true }]}><Select options={students.map((item) => ({ value: item.code, label: `${item.name} · ${item.code}` }))} /></Form.Item><Form.Item name="dueDate" label="Hạn thanh toán" rules={[{ required: true }]}><Input type="date" /></Form.Item><Form.Item label="Học phí"><InputNumber readOnly value={students.find((item) => item.code === selectedStudentCode)?.amount ?? students[0].amount} formatter={(value) => money(Number(value))} style={{ width: '100%' }} /></Form.Item></Form></Modal>
  </AdminLayout>
}
export default AdminInvoices
