import { useMemo, useState } from 'react'
import { CaretRight, Certificate, DownloadSimple, FilePdf, GraduationCap, MagnifyingGlass, Receipt, ShieldCheck, XCircle } from '@phosphor-icons/react'
import { Alert, Avatar, Button, Card, Descriptions, Drawer, Flex, Input, Modal, Select, Space, Table, Tag, Typography, message } from 'antd'
import type { TableProps } from 'antd'
import AdminLayout, { type AdminPage } from './AdminLayout'
import { AdminPageHeader, AdminSummary } from './AdminPageKit'

type CertificateStatus = 'Chờ xét' | 'Đã xác nhận' | 'Đã cấp'
type CertificateFilter = 'Tất cả' | 'Đủ điều kiện' | 'Không đủ điều kiện' | 'Đã cấp'
type Candidate = { id: number; studentCode: string; studentName: string; className: string; course: string; language: string; attendance: number; average: number; paid: boolean; status: CertificateStatus; certificateCode?: string; issuedAt?: string }
type Props = { onLogout: () => void; onNavigate: (page: AdminPage) => void; onNavigateHome: () => void }
const initialCandidates: Candidate[] = [
  { id: 1, studentCode: 'HV-0248', studentName: 'Nguyễn Khánh Linh', className: 'A2 Giao tiếp', course: 'Tiếng Anh A2', language: 'Tiếng Anh', attendance: 82, average: 7.6, paid: true, status: 'Chờ xét' },
  { id: 2, studentCode: 'HV-0217', studentName: 'Trần Gia Huy', className: 'B1 Tổng quát', course: 'Tiếng Anh B1', language: 'Tiếng Anh', attendance: 91, average: 8.2, paid: true, status: 'Đã xác nhận' },
  { id: 3, studentCode: 'HV-0196', studentName: 'Lê Minh Anh', className: 'IELTS 6.5', course: 'Luyện thi IELTS 6.5', language: 'Tiếng Anh', attendance: 76, average: 6.8, paid: false, status: 'Chờ xét' },
  { id: 4, studentCode: 'HV-0173', studentName: 'Phạm Quang Duy', className: 'A2 Giao tiếp', course: 'Tiếng Anh A2', language: 'Tiếng Anh', attendance: 69, average: 4.7, paid: true, status: 'Chờ xét' },
  { id: 5, studentCode: 'HV-0151', studentName: 'Võ Hoàng Nam', className: 'TOPIK I - K05', course: 'Tiếng Hàn TOPIK I', language: 'Tiếng Hàn', attendance: 88, average: 7.9, paid: true, status: 'Đã cấp', certificateCode: 'CC-2026-018', issuedAt: '2026-09-12' },
  { id: 6, studentCode: 'HV-0138', studentName: 'Đặng Thu Trang', className: 'HSK 3 - T04', course: 'Tiếng Trung HSK 3', language: 'Tiếng Trung', attendance: 85, average: 6.5, paid: true, status: 'Chờ xét' },
  { id: 7, studentCode: 'HV-0119', studentName: 'Bùi Thanh Hà', className: 'N4 - N03', course: 'Tiếng Nhật N4', language: 'Tiếng Nhật', attendance: 79, average: 4.9, paid: false, status: 'Chờ xét' },
]
const eligible = (item: Candidate) => item.paid && item.average >= 5
const date = (value: string) => new Intl.DateTimeFormat('vi-VN').format(new Date(`${value}T00:00:00`))

function AdminCertificates({ onLogout, onNavigate, onNavigateHome }: Props) {
  const [candidates, setCandidates] = useState(initialCandidates); const [query, setQuery] = useState(''); const [className, setClassName] = useState('Tất cả'); const [filter, setFilter] = useState<CertificateFilter>('Tất cả')
  const [selectedIds, setSelectedIds] = useState<React.Key[]>([]); const [detail, setDetail] = useState<Candidate | null>(null); const [messageApi, contextHolder] = message.useMessage()
  const [modal, modalContextHolder] = Modal.useModal()
  const confirmedCount = candidates.filter((item) => item.status === 'Đã xác nhận').length
  const data = useMemo(() => candidates.filter((item) => {
    const matches = !query.trim() || [item.studentCode, item.studentName, item.className, item.course, item.certificateCode ?? ''].some((value) => value.toLocaleLowerCase('vi').includes(query.trim().toLocaleLowerCase('vi')))
    const status = filter === 'Tất cả' || (filter === 'Đủ điều kiện' && eligible(item) && item.status !== 'Đã cấp') || (filter === 'Không đủ điều kiện' && !eligible(item)) || (filter === 'Đã cấp' && item.status === 'Đã cấp')
    return matches && status && (className === 'Tất cả' || item.className === className)
  }), [candidates, className, filter, query])
  const confirm = () => modal.confirm({ title: `Xác nhận ${selectedIds.length} học viên?`, content: 'Danh sách đã chọn đáp ứng điều kiện học phí và điểm trung bình.', okText: 'Xác nhận', onOk: () => { setCandidates((current) => current.map((item) => selectedIds.includes(item.id) && eligible(item) ? { ...item, status: 'Đã xác nhận' } : item)); setSelectedIds([]); messageApi.success('Đã xác nhận danh sách.') } })
  const exportPdf = () => modal.confirm({ title: `Kết xuất ${confirmedCount} chứng chỉ?`, content: 'Trạng thái cấp phát sẽ được cập nhật.', okText: 'Kết xuất PDF', onOk: () => { let sequence = Math.max(18, ...candidates.map((item) => Number(item.certificateCode?.split('-').at(-1) ?? 0))); const issuedAt = new Date().toISOString().slice(0, 10); setCandidates((current) => current.map((item) => item.status === 'Đã xác nhận' ? { ...item, status: 'Đã cấp', certificateCode: `CC-2026-${String(++sequence).padStart(3, '0')}`, issuedAt } : item)); setDetail(null); messageApi.success('Đã kết xuất chứng chỉ.') } })
  const columns: TableProps<Candidate>['columns'] = [
    { title: 'Học viên', key: 'student', render: (_, item) => <div className="admin-entity"><Avatar shape="square">{item.studentName.split(' ').slice(-2).map((part) => part[0]).join('')}</Avatar><div><strong>{item.studentName}</strong><small>{item.studentCode}</small></div></div> },
    { title: 'Lớp học', key: 'class', render: (_, item) => <div><Typography.Text strong>{item.className}</Typography.Text><br /><Typography.Text type="secondary">{item.language}</Typography.Text></div> },
    { title: 'Chuyên cần', dataIndex: 'attendance', render: (value) => `${value}%` }, { title: 'Điểm TB', dataIndex: 'average', render: (value) => <Typography.Text type={value < 5 ? 'danger' : undefined} strong>{value.toFixed(1)}</Typography.Text> },
    { title: 'Học phí', dataIndex: 'paid', render: (value) => <Tag color={value ? 'green' : 'red'}>{value ? 'Đã thanh toán' : 'Còn nợ'}</Tag> },
    { title: 'Kết quả', key: 'result', render: (_, item) => <Tag color={item.status === 'Đã cấp' ? 'blue' : !eligible(item) ? 'red' : item.status === 'Đã xác nhận' ? 'gold' : 'green'}>{item.status === 'Chờ xét' ? eligible(item) ? 'Đủ điều kiện' : 'Chưa đạt' : item.status}</Tag> },
    { title: '', key: 'action', width: 52, render: (_, item) => <Button icon={<CaretRight />} onClick={() => setDetail(item)} aria-label={`Xem hồ sơ ${item.studentName}`} /> },
  ]
  return <AdminLayout activePage="certificates" mainId="certificate-management" onLogout={onLogout} onNavigate={onNavigate} onNavigateHome={onNavigateHome}>
    {contextHolder}{modalContextHolder}<AdminPageHeader kicker="Kết quả cuối khóa" title="Thi và chứng chỉ" description="Xét điều kiện, xác nhận danh sách và quản lý lịch sử cấp chứng chỉ." actions={<Space wrap><Button icon={<ShieldCheck />} onClick={confirm} disabled={!selectedIds.length}>Xác nhận ({selectedIds.length})</Button><Button type="primary" icon={<FilePdf />} onClick={exportPdf} disabled={!confirmedCount}>Kết xuất PDF ({confirmedCount})</Button></Space>} />
    <AdminSummary items={[{ label: 'Đủ điều kiện', value: candidates.filter((item) => eligible(item) && item.status !== 'Đã cấp').length, detail: 'Đã thanh toán và điểm từ 5.0', icon: <GraduationCap weight="duotone" />, tone: 'success' }, { label: 'Chưa đủ điều kiện', value: candidates.filter((item) => !eligible(item)).length, detail: 'Còn nợ học phí hoặc điểm dưới 5.0', icon: <XCircle weight="duotone" />, tone: 'danger' }, { label: 'Đã cấp', value: candidates.filter((item) => item.status === 'Đã cấp').length, detail: 'Có thể tra cứu và tải lại PDF', icon: <Certificate weight="duotone" /> }]} />
    <Card className="admin-table-card" title="Danh sách xét cấp" extra={<Space wrap><Input allowClear prefix={<MagnifyingGlass />} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Học viên, lớp hoặc mã" /><Select value={filter} onChange={setFilter} options={['Tất cả', 'Đủ điều kiện', 'Không đủ điều kiện', 'Đã cấp'].map((value) => ({ value, label: value }))} /><Select value={className} onChange={setClassName} options={['Tất cả', ...new Set(candidates.map((item) => item.className))].map((value) => ({ value, label: value }))} /></Space>}><Table rowKey="id" columns={columns} dataSource={data} scroll={{ x: 940 }} rowSelection={{ selectedRowKeys: selectedIds, onChange: setSelectedIds, getCheckboxProps: (item) => ({ disabled: !eligible(item) || item.status !== 'Chờ xét' }) }} pagination={{ pageSize: 6, showTotal: (total) => `${total} học viên` }} /></Card>
    <Drawer size={460} title="Hồ sơ xét cấp" open={Boolean(detail)} onClose={() => setDetail(null)}>{detail && <><Flex align="center" gap={12}><Certificate size={38} /><div><Typography.Title className="admin-drawer-title" level={3}>{detail.studentName}</Typography.Title><Typography.Text type="secondary">{detail.studentCode} · {detail.className}</Typography.Text></div></Flex><Space orientation="vertical" style={{ width: '100%', marginTop: 22 }}><Alert type={detail.paid ? 'success' : 'error'} showIcon icon={<Receipt />} title="Học phí" description={detail.paid ? 'Đã hoàn tất' : 'Chưa hoàn tất'} /><Alert type={detail.average >= 5 ? 'success' : 'error'} showIcon icon={<GraduationCap />} title="Điểm trung bình" description={`${detail.average.toFixed(1)} / 10`} /><Alert type={eligible(detail) ? 'success' : 'warning'} showIcon title={eligible(detail) ? 'Đủ điều kiện cấp chứng chỉ' : 'Chưa đủ điều kiện cấp chứng chỉ'} /></Space>{detail.status === 'Đã cấp' && <><Descriptions bordered column={1} size="small" style={{ marginTop: 20 }} items={[{ key: 'code', label: 'Mã chứng chỉ', children: detail.certificateCode }, { key: 'course', label: 'Khóa học', children: detail.course }, { key: 'issued', label: 'Ngày cấp', children: detail.issuedAt && date(detail.issuedAt) }]} /><Space orientation="vertical" style={{ width: '100%', marginTop: 18 }}><Button block type="primary" icon={<DownloadSimple />} onClick={() => messageApi.info('Tệp PDF sẽ được nhận từ API backend.')}>Tải lại PDF</Button><Button block icon={<Certificate />} onClick={() => messageApi.success(`Đã ghi nhận cấp lại ${detail.certificateCode}`)}>Cấp lại chứng chỉ</Button></Space></>}</>}</Drawer>
  </AdminLayout>
}
export default AdminCertificates
