import { useEffect, useMemo, useState } from 'react'
import { Bank, CaretRight, CheckCircle, CurrencyCircleDollar, MagnifyingGlass, Plus, Receipt, ShieldWarning } from '@phosphor-icons/react'
import { Alert, Avatar, Button, Card, Descriptions, Drawer, Flex, Form, Input, Modal, Select, Space, Table, Tag, Typography, message } from 'antd'
import type { TableProps } from 'antd'
import AdminLayout, { type AdminPage } from './AdminLayout'
import { AdminPageHeader, AdminSummary } from './AdminPageKit'
import { api, errorMessage, json } from '../api'

type InvoiceStatus = 'Chưa thanh toán' | 'Đã thanh toán' | 'Quá hạn' | 'Đã hủy'
type InvoiceRecord = { id: number; code: string; enrollmentId: number; studentCode: string; studentName: string; className: string; course: string; amount: number; issuedAt: string; dueDate: string; status: InvoiceStatus; paidAt?: string; paymentMethod?: string; cancelReason?: string }
type Props = { onLogout: () => void; onNavigate: (page: AdminPage) => void; onNavigateHome: () => void }
type InvoiceApi = { id: number; code: string; enrollmentId: number; studentCode: string; studentName: string; className: string | null; courseName: string; amount: number; issuedAt: string; dueDate: string; status: string; paidAt: string | null; paymentMethod: string | null; cancellationReason: string | null }
type EnrollmentOption = { id: number; studentCode: string; studentName: string; courseName: string; className: string | null; status: string }
const money = (value: number) => `${new Intl.NumberFormat('vi-VN').format(value)}đ`
const date = (value: string) => new Intl.DateTimeFormat('vi-VN').format(new Date(`${value}T00:00:00`))
const colors: Record<InvoiceStatus, string> = { 'Chưa thanh toán': 'gold', 'Đã thanh toán': 'green', 'Quá hạn': 'red', 'Đã hủy': 'default' }

function AdminInvoices({ onLogout, onNavigate, onNavigateHome }: Props) {
  const [invoices, setInvoices] = useState<InvoiceRecord[]>([])
  const [enrollments, setEnrollments] = useState<EnrollmentOption[]>([])
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<'Tất cả' | InvoiceStatus>('Tất cả'); const [className, setClassName] = useState('Tất cả')
  const [selected, setSelected] = useState<InvoiceRecord | null>(null); const [creating, setCreating] = useState(false)
  const [canceling, setCanceling] = useState<InvoiceRecord | null>(null); const [cancelReason, setCancelReason] = useState(''); const [cancelLoading, setCancelLoading] = useState(false)
  const [form] = Form.useForm<{ enrollmentId: number; dueDate: string }>(); const [messageApi, contextHolder] = message.useMessage()
  const [modal, modalContextHolder] = Modal.useModal()
  const data = useMemo(() => invoices.filter((item) => (!query.trim() || [item.code, item.studentCode, item.studentName, item.className].some((value) => value.toLocaleLowerCase('vi').includes(query.trim().toLocaleLowerCase('vi')))) && (status === 'Tất cả' || item.status === status) && (className === 'Tất cả' || item.className === className)), [className, invoices, query, status])
  const load = async () => { try { const [rows, enrollmentRows] = await Promise.all([api<InvoiceApi[]>('/invoices'), api<EnrollmentOption[]>('/enrollments')]); const statusMap: Record<string, InvoiceStatus> = { chua_thanh_toan: 'Chưa thanh toán', da_thanh_toan: 'Đã thanh toán', qua_han: 'Quá hạn', da_huy: 'Đã hủy' }; setEnrollments(enrollmentRows); setInvoices(rows.map((item) => ({ id: item.id, code: item.code, enrollmentId: item.enrollmentId, studentCode: item.studentCode, studentName: item.studentName, className: item.className ?? 'Chưa xếp lớp', course: item.courseName, amount: Number(item.amount), issuedAt: String(item.issuedAt).slice(0, 10), dueDate: String(item.dueDate).slice(0, 10), status: statusMap[item.status], paidAt: item.paidAt ? String(item.paidAt).slice(0, 10) : undefined, paymentMethod: item.paymentMethod === 'chuyen_khoan' ? 'Chuyển khoản' : item.paymentMethod === 'tien_mat' ? 'Tiền mặt' : undefined, cancelReason: item.cancellationReason ?? undefined }))) } catch (error) { messageApi.error(errorMessage(error)) } }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [])
  const create = async (values: { enrollmentId: number; dueDate: string }) => { try { await api('/invoices', json('POST', values)); setCreating(false); await load(); messageApi.success('Đã tạo hóa đơn.') } catch (error) { messageApi.error(errorMessage(error)) } }
  const pay = (invoice: InvoiceRecord) => modal.confirm({ title: 'Xác nhận thanh toán?', content: `${invoice.studentName} · ${money(invoice.amount)}`, okText: 'Xác nhận', onOk: async () => { try { await api(`/invoices/${invoice.id}/payment`, json('PATCH', { method: 'chuyen_khoan' })); setSelected(null); await load(); messageApi.success('Đã xác nhận thanh toán.') } catch (error) { messageApi.error(errorMessage(error)) } } })
  const cancel = (invoice: InvoiceRecord) => { if (invoice.status === 'Đã thanh toán') { messageApi.error('Không thể hủy hóa đơn đã thanh toán.'); return }; setCancelReason(''); setCanceling(invoice) }
  const confirmCancel = async () => { if (!canceling || !cancelReason.trim()) return; setCancelLoading(true); try { await api(`/invoices/${canceling.id}/cancel`, json('PATCH', { reason: cancelReason.trim() })); setCanceling(null); setSelected(null); await load(); messageApi.success('Đã hủy hóa đơn.') } catch (error) { messageApi.error(errorMessage(error)) } finally { setCancelLoading(false) } }
  const columns: TableProps<InvoiceRecord>['columns'] = [
    { title: 'Hóa đơn', key: 'invoice', render: (_, item) => <div><Typography.Text strong>{item.code}</Typography.Text><br /><Typography.Text type="secondary">{date(item.issuedAt)}</Typography.Text></div> },
    { title: 'Học viên', key: 'student', render: (_, item) => <div className="admin-entity"><Avatar shape="square">{item.studentName.split(' ').slice(-2).map((part) => part[0]).join('')}</Avatar><div><strong>{item.studentName}</strong><small>{item.studentCode}</small></div></div> },
    { title: 'Lớp học', dataIndex: 'className' }, { title: 'Số tiền', dataIndex: 'amount', render: (value) => <Typography.Text strong>{money(value)}</Typography.Text> }, { title: 'Hạn thanh toán', dataIndex: 'dueDate', render: date },
    { title: 'Trạng thái', dataIndex: 'status', render: (value: InvoiceStatus) => <Tag color={colors[value]}>{value}</Tag> }, { title: '', key: 'action', width: 52, render: (_, item) => <Button icon={<CaretRight />} onClick={() => setSelected(item)} aria-label={`Xem hóa đơn ${item.code}`} /> },
  ]
  return <AdminLayout activePage="invoices" mainId="invoice-management" onLogout={onLogout} onNavigate={onNavigate} onNavigateHome={onNavigateHome}>
    {contextHolder}{modalContextHolder}<AdminPageHeader kicker="Tài chính học vụ" title="Quản lý học phí" description="Theo dõi hóa đơn, công nợ và điều kiện dự thi của học viên." actions={<Button type="primary" icon={<Plus />} onClick={() => { setCreating(true); form.setFieldsValue({ enrollmentId: enrollments[0]?.id, dueDate: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10) }) }}>Tạo hóa đơn</Button>} />
    <AdminSummary items={[{ label: 'Đã thu', value: money(invoices.filter((item) => item.status === 'Đã thanh toán').reduce((sum, item) => sum + item.amount, 0)).replace('đ', ''), detail: 'VNĐ đã xác nhận thanh toán', icon: <Bank weight="duotone" />, tone: 'success' }, { label: 'Công nợ', value: money(invoices.filter((item) => ['Chưa thanh toán', 'Quá hạn'].includes(item.status)).reduce((sum, item) => sum + item.amount, 0)).replace('đ', ''), detail: 'VNĐ chưa hoàn tất', icon: <CurrencyCircleDollar weight="duotone" /> }, { label: 'Hóa đơn quá hạn', value: invoices.filter((item) => item.status === 'Quá hạn').length, detail: 'Tạm khóa quyền dự thi', icon: <ShieldWarning weight="duotone" />, tone: 'danger' }]} />
    <Card className="admin-table-card" title="Danh sách hóa đơn" extra={<Space wrap><Input allowClear prefix={<MagnifyingGlass />} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Mã, học viên hoặc lớp" /><Select value={status} onChange={setStatus} options={['Tất cả', 'Chưa thanh toán', 'Đã thanh toán', 'Quá hạn', 'Đã hủy'].map((value) => ({ value, label: value }))} /><Select value={className} onChange={setClassName} options={['Tất cả', ...new Set(invoices.map((item) => item.className))].map((value) => ({ value, label: value }))} /></Space>}><Table rowKey="id" columns={columns} dataSource={data} scroll={{ x: 980 }} pagination={{ pageSize: 6, showTotal: (total) => `${total} hóa đơn` }} /></Card>
    <Drawer size={450} title="Chi tiết hóa đơn" open={Boolean(selected)} onClose={() => setSelected(null)}>{selected && <><Flex align="center" gap={12}><Receipt size={36} /><div><Typography.Title className="admin-drawer-title" level={3}>{selected.code}</Typography.Title><Typography.Text type="secondary">{selected.studentName} · {selected.studentCode}</Typography.Text></div></Flex><Card style={{ marginTop: 22, background: '#e8f1e8' }}><Flex justify="space-between"><Typography.Text>Tổng học phí</Typography.Text><Typography.Title level={3} style={{ margin: 0 }}>{money(selected.amount)}</Typography.Title></Flex></Card><Descriptions bordered column={1} size="small" style={{ marginTop: 18 }} items={[{ key: 'course', label: 'Khóa học', children: selected.course }, { key: 'issued', label: 'Ngày tạo', children: date(selected.issuedAt) }, { key: 'due', label: 'Hạn thanh toán', children: date(selected.dueDate) }, ...(selected.paidAt ? [{ key: 'paid', label: 'Đã thanh toán', children: `${date(selected.paidAt)} · ${selected.paymentMethod}` }] : []), ...(selected.cancelReason ? [{ key: 'cancel', label: 'Lý do hủy', children: selected.cancelReason }] : [])]} /><Alert style={{ marginTop: 18 }} type={selected.status === 'Đã thanh toán' ? 'success' : 'warning'} showIcon title={selected.status === 'Đã thanh toán' ? 'Đã mở khóa điều kiện tài chính' : 'Tạm khóa do học phí'} /><Space orientation="vertical" style={{ width: '100%', marginTop: 18 }}>{['Chưa thanh toán', 'Quá hạn'].includes(selected.status) && <Button block type="primary" icon={<CheckCircle />} onClick={() => pay(selected)}>Xác nhận thanh toán</Button>}<Button block danger onClick={() => cancel(selected)} disabled={selected.status === 'Đã hủy'}>Hủy hóa đơn</Button></Space></>}</Drawer>
    <Modal title="Tạo hóa đơn" open={creating} onCancel={() => setCreating(false)} onOk={() => form.submit()} okText="Tạo hóa đơn" destroyOnHidden><Form form={form} layout="vertical" onFinish={create} style={{ marginTop: 20 }}><Form.Item name="enrollmentId" label="Ghi danh" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={enrollments.filter((item) => item.status !== 'da_huy').map((item) => ({ value: item.id, label: `${item.studentName} · ${item.studentCode} · ${item.courseName}` }))} /></Form.Item><Form.Item name="dueDate" label="Hạn thanh toán" rules={[{ required: true }]}><Input type="date" /></Form.Item></Form></Modal>
    <Modal title={`Hủy hóa đơn ${canceling?.code ?? ''}`} open={Boolean(canceling)} okText="Xác nhận hủy" cancelText="Quay lại" okButtonProps={{ danger: true, disabled: !cancelReason.trim() }} confirmLoading={cancelLoading} onCancel={() => setCanceling(null)} onOk={() => void confirmCancel()} destroyOnHidden><Typography.Paragraph type="secondary">Nhập lý do để lưu vào lịch sử hóa đơn.</Typography.Paragraph><Input.TextArea rows={4} value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} placeholder="Lý do hủy hóa đơn" maxLength={500} showCount autoFocus /></Modal>
  </AdminLayout>
}
export default AdminInvoices
